// Pure generators that turn an AuditReport into ready-to-deploy indexing files
// (robots.txt, llms.txt, llms-full.txt, .well-known/ai.json, sitemap.xml,
// jsonld-stubs.json) plus a writer. Isolated module: no dependency on index.ts
// or runner.ts, importable from the CLI (--emit, a later task) and from
// apps/web (self-apply flow, another later task).
//
// Every generator is a pure `(report, {lang}) => string` function (sitemap.xml
// has no per-page language content, so it skips the {lang} option). Content is
// intentionally generic — a starting point to personalize, never fabricated
// prose — and every file carries a "review before deploying, especially
// robots.txt" warning localized to `lang`.

import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import type { AuditReport } from '../runner.js';
import type { Lang } from '../report/i18n.js';
import { TRAINING_BOTS, CITATION_BOTS } from '../robots.js';

export interface GenerateOptions {
  lang: Lang;
}

// ---------------------------------------------------------------------------
// Shared bilingual warning text
// ---------------------------------------------------------------------------

function warnText(lang: Lang): string {
  return lang === 'fr'
    ? 'Généré par findable-audit — relire avant de déployer, surtout robots.txt.'
    : 'Generated by findable-audit — review before deploying, especially robots.txt.';
}

function warnDetail(lang: Lang): string {
  return lang === 'fr'
    ? 'Contenu générique à personnaliser avant publication.'
    : 'Generic content: personalize it before publishing.';
}

function warnNote(lang: Lang): string {
  return `${warnText(lang)} ${warnDetail(lang)}`;
}

// ---------------------------------------------------------------------------
// Shared bilingual "to complete" guidance — a consistent, greppable marker
// convention: `<... à compléter>` (fr) / `<... to fill in>` (en) placeholders,
// plus `REPLACE_ME` / `Q00000000` for opaque IDs. Every generated file also
// carries a short guidance block, in its own native format, that says what
// its OWN gaps are and how to fill them; GENERATED-README.md repeats the
// same guidance once per file so it can be read without opening each file.
// ---------------------------------------------------------------------------

/** Per-file "what to complete" tip, one sentence, reused by both the README and (where relevant) the file body. */
function toCompleteTip(filename: string, lang: Lang): string {
  const tips: Record<string, { fr: string; en: string }> = {
    'robots.txt': {
      fr: 'vérifiez la liste des bots ci-dessous ; pour BLOQUER un robot, décommentez la ligne `Disallow: /` sous son bloc `User-agent` ; confirmez l’URL de la ligne `Sitemap:`.',
      en: 'review the bot list below; to BLOCK a crawler, uncomment the `Disallow: /` line under its `User-agent` block; confirm the `Sitemap:` URL.',
    },
    'llms.txt': {
      fr: 'remplacez le résumé générique par votre vraie description (1-2 phrases) ; complétez/curatez les liens de chaque section `##`.',
      en: 'replace the generic summary with your real description (1-2 sentences); complete/curate each `##` section’s links.',
    },
    'llms-full.txt': {
      fr: 'squelette : remplissez chaque section avec votre vrai contenu (visez ≥2000 mots au total pour être utile aux LLM).',
      en: 'stub: fill each section with your real content (aim for ≥2000 words total to be useful to LLMs).',
    },
    '.well-known/ai.json': {
      fr: 'renseignez un contact réel et confirmez la politique d’accès des bots (`ai_access.policy`).',
      en: 'fill in a real contact and confirm the bots access policy (`ai_access.policy`).',
    },
    'sitemap.xml': {
      fr: 'ajoutez les pages absentes de cet échantillon et renseignez les dates `lastmod`.',
      en: 'add the pages missing from this sample and fill in the `lastmod` dates.',
    },
    'jsonld-stubs.json': {
      fr: 'remplacez `<… à compléter>`, `REPLACE_ME` (URL Wikipédia), `Q00000000` (ID Wikidata) et l’URL du logo ; fusionnez le `@graph` dans votre JSON-LD existant.',
      en: 'replace `<… to fill in>`, `REPLACE_ME` (Wikipedia URL), `Q00000000` (Wikidata ID) and the logo URL; merge the `@graph` into your existing JSON-LD.',
    },
  };
  const tip = tips[filename];
  return lang === 'fr' ? tip.fr : tip.en;
}

/** The GENERATED-README.md "to complete" section: one bullet per generated file, plus the greppable markers. */
function toCompleteSection(lang: Lang): string {
  const header = lang === 'fr' ? '## À compléter' : '## To complete';
  const intro = lang === 'fr'
    ? 'Avant de déployer, remplissez ces fichiers un par un :'
    : 'Before deploying, fill in these files one by one:';
  const list = EMITTED_FILES.map((f) => `- \`${f.filename}\`: ${toCompleteTip(f.filename, lang)}`).join('\n');
  const footer = lang === 'fr'
    ? 'Cherchez les marqueurs `à compléter`, `REPLACE_ME` et `Q00000000` dans les fichiers pour retrouver tout ce qui reste à remplir.'
    : 'Search for the `to fill in`, `REPLACE_ME` and `Q00000000` markers across the files to find everything left to fill in.';
  return [header, '', intro, '', list, '', footer].join('\n');
}

// ---------------------------------------------------------------------------
// generateRobotsTxt
// ---------------------------------------------------------------------------

export function generateRobotsTxt(report: AuditReport, { lang }: GenerateOptions): string {
  const origin = new URL(report.url).origin;
  const lines: string[] = [];
  lines.push(`# ${warnText(lang)}`);
  lines.push(`# ${warnDetail(lang)}`);
  lines.push('');
  lines.push(lang === 'fr' ? '# À COMPLÉTER :' : '# TO COMPLETE:');
  lines.push(lang === 'fr'
    ? '# - Vérifiez la liste de bots ci-dessous (entraînement / citation).'
    : '# - Review the bot list below (training / citation).');
  lines.push(lang === 'fr'
    ? '# - Pour BLOQUER un robot, décommentez la ligne "Disallow: /" sous son bloc "User-agent".'
    : '# - To BLOCK a crawler, uncomment the "Disallow: /" line under its "User-agent" block.');
  lines.push(lang === 'fr'
    ? '# - Confirmez que la ligne "Sitemap:" en bas de ce fichier pointe vers votre vrai sitemap.'
    : '# - Confirm the "Sitemap:" line at the bottom of this file points at your real sitemap.');
  lines.push('');
  lines.push('User-agent: *');
  lines.push('Allow: /');
  lines.push('');
  lines.push(lang === 'fr'
    ? '# --- Crawlers IA "entraînement" (utilisés pour entraîner de futurs modèles) ---'
    : '# --- Training-time AI crawlers (used to train future models) ---');
  lines.push(lang === 'fr'
    ? "# Les bloquer est un choix de politique, pas une obligation technique : pour"
    : '# Blocking these is a policy choice, not a technical requirement: to opt a');
  lines.push(lang === 'fr'
    ? "# exclure un bot de l'entraînement, décommentez la ligne \"Disallow: /\" sous lui."
    : '# bot out of training, uncomment the "Disallow: /" line right below it.');
  lines.push('');
  for (const bot of TRAINING_BOTS) {
    lines.push(`User-agent: ${bot}`);
    lines.push('Allow: /');
    lines.push('# Disallow: /');
    lines.push('');
  }
  lines.push(lang === 'fr'
    ? '# --- Fetchers IA "citation" (utilisés en direct, au moment de la réponse) ---'
    : '# --- Citation-time AI fetchers (used live, at answer time) ---');
  lines.push(lang === 'fr'
    ? '# Les bloquer masque votre site des réponses générées par IA.'
    : '# Blocking these hides your site from AI-generated answers/citations.');
  lines.push('');
  for (const bot of CITATION_BOTS) {
    lines.push(`User-agent: ${bot}`);
    lines.push('Allow: /');
    lines.push('');
  }
  lines.push(`Sitemap: ${origin}/sitemap.xml`);
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// llms.txt / llms-full.txt shared helpers
// ---------------------------------------------------------------------------

/** A readable, always-descriptive (>=2 words) title derived from a pathname. */
function pageTitle(pathname: string, host: string, lang: Lang): string {
  if (pathname === '/' || pathname === '') {
    return lang === 'fr' ? `Accueil de ${host}` : `Homepage of ${host}`;
  }
  const words = pathname
    .split('/')
    .filter(Boolean)
    .flatMap((seg) => seg.split(/[-_]+/))
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1));
  const label = words.join(' ') || pathname;
  return lang === 'fr' ? `Page ${label}` : `${label} page`;
}

function samplePagesOrRoot(report: AuditReport): string[] {
  return report.sampledPages.length > 0 ? report.sampledPages : ['/'];
}

// ---------------------------------------------------------------------------
// generateLlmsTxt
// ---------------------------------------------------------------------------

export function generateLlmsTxt(report: AuditReport, { lang }: GenerateOptions): string {
  const base = new URL(report.url);
  const host = base.host;
  const lines: string[] = [];
  lines.push(`# ${host}`);
  lines.push('');
  lines.push(`<!-- ${warnNote(lang)} -->`);
  lines.push('');
  lines.push(lang === 'fr'
    ? `> Ébauche générée automatiquement pour ${host}. Remplacez ce résumé par 2-3`
    : `> Auto-generated stub for ${host}. Replace this summary with 2-3`);
  lines.push(lang === 'fr'
    ? "> phrases décrivant ce que propose le site et à qui il s'adresse."
    : '> sentences describing what the site offers and who it is for.');
  lines.push('');
  lines.push(lang === 'fr' ? '## Pages' : '## Pages');
  lines.push('');
  for (const p of samplePagesOrRoot(report)) {
    const abs = new URL(p, report.url).toString();
    lines.push(`- [${pageTitle(p, host, lang)}](${abs})`);
  }
  lines.push('');
  // Guidance appended AFTER the real sections/links, as an HTML comment, so it
  // cannot be mistaken for a "## Section" or a descriptive link by the
  // llms-txt check (H1 + summary + >=1 "## " section + >=5 same-origin links).
  lines.push(lang === 'fr'
    ? '<!-- À COMPLÉTER : remplacez le résumé ci-dessus par votre vraie description (1-2 phrases) ; complétez/curatez les liens de chaque section "##". -->'
    : '<!-- TO COMPLETE: replace the summary above with your real description (1-2 sentences); complete/curate each "##" section\'s links. -->');
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// generateLlmsFullTxt
// ---------------------------------------------------------------------------

export function generateLlmsFullTxt(report: AuditReport, { lang }: GenerateOptions): string {
  const base = new URL(report.url);
  const host = base.host;
  const lines: string[] = [];
  lines.push(lang === 'fr' ? `# ${host} — contenu complet (ébauche générée)` : `# ${host} — full content (generated stub)`);
  lines.push('');
  lines.push(`<!-- ${warnNote(lang)} -->`);
  lines.push('');
  lines.push(lang === 'fr'
    ? 'Ce fichier doit contenir le texte intégral de vos pages clés, sous des titres,'
    : 'This file should hold the full text content of your key pages, under');
  lines.push(lang === 'fr'
    ? "pour les systèmes IA qui récupèrent un document consolidé unique. Ci-dessous,"
    : 'headings, for AI systems that fetch a single consolidated document. Below is');
  lines.push(lang === 'fr'
    ? 'une ébauche structurelle : remplacez chaque commentaire "À COMPLÉTER" par le vrai contenu de la page (visez ≥2000 mots au total).'
    : 'a structural stub — replace each "TO COMPLETE" comment with the real page content (aim for ≥2000 words total).');
  lines.push('');
  for (const p of samplePagesOrRoot(report)) {
    lines.push(`## ${pageTitle(p, host, lang)}`);
    lines.push('');
    lines.push(lang === 'fr'
      ? `<!-- À COMPLÉTER : collez ici le texte complet de la page ${p}. -->`
      : `<!-- TO COMPLETE: paste the full text content of ${p} here. -->`);
    lines.push('');
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// generateAiJson
// ---------------------------------------------------------------------------

export function generateAiJson(report: AuditReport, { lang }: GenerateOptions): string {
  const url = new URL(report.url);
  const obj = {
    name: url.host,
    description: lang === 'fr'
      ? `Ébauche générée automatiquement pour ${url.host}. Remplacez cette description par une présentation réelle du site/de l'organisation.`
      : `Auto-generated stub for ${url.host}. Replace this description with a real summary of the site/organization.`,
    contact: `${url.origin}/`,
    ai_access: {
      training_bots: [...TRAINING_BOTS],
      citation_bots: [...CITATION_BOTS],
      policy: 'allow',
    },
    _note: warnNote(lang),
    _to_complete: lang === 'fr'
      ? [
        "Renseignez un contact réel (email, formulaire...) à la place de l'URL par défaut ci-dessus.",
        "Confirmez que ai_access.policy reflète votre politique réelle d'accès aux bots (vous pouvez aussi la préciser bot par bot).",
      ]
      : [
        'Fill in a real contact (email, form…) instead of the default URL above.',
        'Confirm ai_access.policy reflects your actual bot access policy (you can also refine it bot by bot).',
      ],
  };
  return `${JSON.stringify(obj, null, 2)}\n`;
}

// ---------------------------------------------------------------------------
// generateSitemapXml (no {lang}: URLs carry no language-specific content)
// ---------------------------------------------------------------------------

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

export function generateSitemapXml(report: AuditReport): string {
  const urls = samplePagesOrRoot(report).map((p) => new URL(p, report.url).toString());
  const body = urls.map((u) => `  <url>\n    <loc>${escapeXml(u)}</loc>\n  </url>`).join('\n');
  // XML comments carry raw text (entities are not expanded inside them), so this
  // is not escapeXml()'d — only "--" is disallowed in a comment, and there is none here.
  const toComplete = 'TO COMPLETE: add the page(s) missing from this sample and fill in real lastmod dates per URL.'
    + ' / À COMPLÉTER : ajoutez la ou les pages absentes de cet échantillon et renseignez de vraies dates lastmod par URL.';
  return `<?xml version="1.0" encoding="UTF-8"?>\n`
    + `<!-- ${warnText('en')} / ${warnText('fr')} -->\n`
    + `<!-- ${toComplete} -->\n`
    + `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

// ---------------------------------------------------------------------------
// generateJsonLdStubs
// ---------------------------------------------------------------------------

const STUB_ROOT_TYPES = ['Organization', 'WebSite', 'BreadcrumbList', 'FAQPage'] as const;
type StubRootType = (typeof STUB_ROOT_TYPES)[number];

/** Schema.org @type values already present anywhere in the sampled entity graph (empty when unknown). */
function presentTypes(report: AuditReport): Set<string> {
  const nodes = report.entityGraph?.nodes;
  if (!nodes) return new Set();
  const set = new Set<string>();
  for (const n of nodes) for (const t of n.types) set.add(t);
  return set;
}

export function generateJsonLdStubs(report: AuditReport, { lang }: GenerateOptions): string {
  const url = new URL(report.url);
  const origin = url.origin;
  const host = url.host;
  const present = presentTypes(report);
  const missing: StubRootType[] = STUB_ROOT_TYPES.filter((t) => !present.has(t));

  const orgId = `${origin}/#org`;
  const siteId = `${origin}/#website`;
  const graph: Record<string, unknown>[] = [];

  if (missing.includes('Organization')) {
    graph.push({
      '@type': 'Organization',
      '@id': orgId,
      name: lang === 'fr' ? `<Nom de l'organisation à compléter> (${host})` : `<Organization name to fill in> (${host})`,
      url: `${origin}/`,
      logo: `https://${host}/logo.png`,
      sameAs: [
        'https://en.wikipedia.org/wiki/REPLACE_ME',
        'https://www.wikidata.org/wiki/Q00000000',
      ],
    });
  }
  if (missing.includes('WebSite')) {
    const site: Record<string, unknown> = {
      '@type': 'WebSite',
      '@id': siteId,
      url: `${origin}/`,
      name: lang === 'fr' ? '<Nom du site à compléter>' : '<Site name to fill in>',
      potentialAction: {
        '@type': 'SearchAction',
        target: { '@type': 'EntryPoint', urlTemplate: `${origin}/search?q={search_term_string}` },
        'query-input': 'required name=search_term_string',
      },
    };
    if (missing.includes('Organization')) site.publisher = { '@id': orgId };
    graph.push(site);
  }
  if (missing.includes('BreadcrumbList')) {
    graph.push({
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: lang === 'fr' ? 'Accueil' : 'Home', item: `${origin}/` },
        { '@type': 'ListItem', position: 2, name: lang === 'fr' ? '<Page actuelle à compléter>' : '<Current page to fill in>' },
      ],
    });
  }
  if (missing.includes('FAQPage')) {
    graph.push({
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: lang === 'fr' ? '<Question exemple à compléter>' : '<Example question to fill in>',
          acceptedAnswer: {
            '@type': 'Answer',
            text: lang === 'fr' ? '<Réponse exemple à compléter>' : '<Example answer to fill in>',
          },
        },
      ],
    });
  }

  const extra = graph.length === 0
    ? (lang === 'fr'
      ? ' Aucune ébauche nécessaire : Organization, WebSite, BreadcrumbList et FAQPage sont déjà présents sur le site.'
      : ' No stub needed: Organization, WebSite, BreadcrumbList and FAQPage are already present on the site.')
    : (lang === 'fr'
      ? ' Fusionnez ce @graph avec votre JSON-LD existant, ou ajoutez-le comme nouveau <script type="application/ld+json">.'
      : ' Merge this @graph into your existing JSON-LD, or add it as a new <script type="application/ld+json">.');

  const toComplete: string[] = [];
  if (missing.includes('Organization')) {
    toComplete.push(lang === 'fr'
      ? "Organization : remplacez <Nom de l'organisation à compléter>, l'URL Wikipédia REPLACE_ME, l'ID Wikidata Q00000000 et l'URL du logo par les vraies valeurs."
      : 'Organization: replace <Organization name to fill in>, the REPLACE_ME Wikipedia URL, the Q00000000 Wikidata ID and the logo URL with real values.');
  }
  if (missing.includes('WebSite')) {
    toComplete.push(lang === 'fr'
      ? '<Nom du site à compléter> : remplacez-le par le vrai nom du site.'
      : '<Site name to fill in>: replace it with the real site name.');
  }
  if (missing.includes('BreadcrumbList')) {
    toComplete.push(lang === 'fr'
      ? '<Page actuelle à compléter> : remplacez-le par le nom réel de la page courante.'
      : '<Current page to fill in>: replace it with the real name of the current page.');
  }
  if (missing.includes('FAQPage')) {
    toComplete.push(lang === 'fr'
      ? '<Question exemple à compléter> / <Réponse exemple à compléter> : remplacez-les par une vraie question et sa vraie réponse.'
      : '<Example question to fill in> / <Example answer to fill in>: replace them with a real question and its real answer.');
  }
  if (toComplete.length > 0) {
    toComplete.push(lang === 'fr'
      ? 'Fusionnez ensuite ce @graph dans le JSON-LD existant de vos pages.'
      : "Then merge this @graph into your pages' existing JSON-LD.");
  }

  const out = {
    '@context': 'https://schema.org',
    '@graph': graph,
    _note: `${warnNote(lang)}${extra}`,
    _to_complete: toComplete,
  };
  return `${JSON.stringify(out, null, 2)}\n`;
}

// ---------------------------------------------------------------------------
// EMITTED_FILES — single source of truth shared with the CLI (--emit) and web
// (self-apply) surfaces, wired up by later tasks.
// ---------------------------------------------------------------------------

export interface EmittedFile {
  /** Relative path within the output directory (may include subdirectories, e.g. ".well-known/ai.json"). */
  filename: string;
  mime: string;
  build(report: AuditReport, opts: GenerateOptions): string;
}

export const EMITTED_FILES: ReadonlyArray<EmittedFile> = [
  { filename: 'robots.txt', mime: 'text/plain', build: generateRobotsTxt },
  { filename: 'llms.txt', mime: 'text/plain', build: generateLlmsTxt },
  { filename: 'llms-full.txt', mime: 'text/plain', build: generateLlmsFullTxt },
  { filename: '.well-known/ai.json', mime: 'application/json', build: generateAiJson },
  { filename: 'sitemap.xml', mime: 'application/xml', build: (report) => generateSitemapXml(report) },
  { filename: 'jsonld-stubs.json', mime: 'application/json', build: generateJsonLdStubs },
];

// ---------------------------------------------------------------------------
// generateReadme + emitFiles
// ---------------------------------------------------------------------------

export function generateReadme(report: AuditReport, { lang }: GenerateOptions): string {
  const host = new URL(report.url).host;
  const title = lang === 'fr' ? `Fichiers générés pour ${host}` : `Generated files for ${host}`;
  const intro = lang === 'fr'
    ? `Ces fichiers ont été générés automatiquement par findable-audit à partir de l'audit de ${host}. ${warnText(lang)} Bloquer un crawler IA par erreur peut retirer votre site des réponses générées par IA.`
    : `These files were auto-generated by findable-audit from the audit of ${host}. ${warnText(lang)} Accidentally blocking an AI crawler can remove your site from AI-generated answers.`;
  const list = EMITTED_FILES.map((f) => `- \`${f.filename}\``).join('\n');
  const placement = lang === 'fr'
    ? 'Placez `robots.txt`, `llms.txt`, `llms-full.txt` et `sitemap.xml` à la racine du site, et `.well-known/ai.json` sous `/.well-known/`. Le contenu de `jsonld-stubs.json` est à fusionner dans le JSON-LD existant de vos pages (balise `<script type="application/ld+json">`).'
    : 'Place `robots.txt`, `llms.txt`, `llms-full.txt` and `sitemap.xml` at the site root, and `.well-known/ai.json` under `/.well-known/`. The content of `jsonld-stubs.json` should be merged into your pages\' existing JSON-LD (`<script type="application/ld+json">` tag).';
  return [
    `# ${title}`,
    '',
    intro,
    '',
    lang === 'fr' ? '## Fichiers' : '## Files',
    '',
    list,
    '',
    placement,
    '',
    toCompleteSection(lang),
    '',
  ].join('\n');
}

/** Write every EMITTED_FILES entry plus GENERATED-README.md into `dir`. Returns the written paths. */
export function emitFiles(report: AuditReport, dir: string, { lang }: GenerateOptions): string[] {
  const written: string[] = [];
  for (const entry of EMITTED_FILES) {
    const full = path.join(dir, entry.filename);
    mkdirSync(path.dirname(full), { recursive: true });
    writeFileSync(full, entry.build(report, { lang }), 'utf8');
    written.push(full);
  }
  const readmePath = path.join(dir, 'GENERATED-README.md');
  mkdirSync(dir, { recursive: true });
  writeFileSync(readmePath, generateReadme(report, { lang }), 'utf8');
  written.push(readmePath);
  return written;
}
