// Pure generators that turn an AuditReport into ready-to-deploy indexing files
// (robots.txt, llms.txt, llms-full.txt, .well-known/ai.json, sitemap.xml,
// jsonld-stubs.json) plus a writer. Isolated module: no dependency on index.ts
// or runner.ts, importable from the CLI (--emit, a later task) and from
// apps/web (self-apply flow, another later task).
//
// Every generator is a pure `(report, {lang}) => string` function (sitemap.xml
// has no per-page language content, so it skips the {lang} option). Content is
// intentionally generic — a starting point to personalize, never fabricated
// prose — and every file carries a "review before deploying, especially
// robots.txt" warning localized to `lang`.

import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import type { AuditReport } from '../runner.js';
import type { Lang } from '../report/i18n.js';
import { TRAINING_BOTS, CITATION_BOTS } from '../robots.js';

export interface GenerateOptions {
  lang: Lang;
}

// ---------------------------------------------------------------------------
// Shared bilingual warning text
// ---------------------------------------------------------------------------

function warnText(lang: Lang): string {
  return lang === 'fr'
    ? 'Généré par findable-audit — relire avant de déployer, surtout robots.txt.'
    : 'Generated by findable-audit — review before deploying, especially robots.txt.';
}

function warnDetail(lang: Lang): string {
  return lang === 'fr'
    ? 'Contenu générique à personnaliser avant publication.'
    : 'Generic content: personalize it before publishing.';
}

function warnNote(lang: Lang): string {
  return `${warnText(lang)} ${warnDetail(lang)}`;
}

// ---------------------------------------------------------------------------
// generateRobotsTxt
// ---------------------------------------------------------------------------

export function generateRobotsTxt(report: AuditReport, { lang }: GenerateOptions): string {
  const origin = new URL(report.url).origin;
  const lines: string[] = [];
  lines.push(`# ${warnText(lang)}`);
  lines.push(`# ${warnDetail(lang)}`);
  lines.push('');
  lines.push('User-agent: *');
  lines.push('Allow: /');
  lines.push('');
  lines.push(lang === 'fr'
    ? '# --- Crawlers IA "entraînement" (utilisés pour entraîner de futurs modèles) ---'
    : '# --- Training-time AI crawlers (used to train future models) ---');
  lines.push(lang === 'fr'
    ? "# Les bloquer est un choix de politique, pas une obligation technique : pour"
    : '# Blocking these is a policy choice, not a technical requirement: to opt a');
  lines.push(lang === 'fr'
    ? "# exclure un bot de l'entraînement, décommentez la ligne \"Disallow: /\" sous lui."
    : '# bot out of training, uncomment the "Disallow: /" line right below it.');
  lines.push('');
  for (const bot of TRAINING_BOTS) {
    lines.push(`User-agent: ${bot}`);
    lines.push('Allow: /');
    lines.push('# Disallow: /');
    lines.push('');
  }
  lines.push(lang === 'fr'
    ? '# --- Fetchers IA "citation" (utilisés en direct, au moment de la réponse) ---'
    : '# --- Citation-time AI fetchers (used live, at answer time) ---');
  lines.push(lang === 'fr'
    ? '# Les bloquer masque votre site des réponses générées par IA.'
    : '# Blocking these hides your site from AI-generated answers/citations.');
  lines.push('');
  for (const bot of CITATION_BOTS) {
    lines.push(`User-agent: ${bot}`);
    lines.push('Allow: /');
    lines.push('');
  }
  lines.push(`Sitemap: ${origin}/sitemap.xml`);
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// llms.txt / llms-full.txt shared helpers
// ---------------------------------------------------------------------------

/** A readable, always-descriptive (>=2 words) title derived from a pathname. */
function pageTitle(pathname: string, host: string, lang: Lang): string {
  if (pathname === '/' || pathname === '') {
    return lang === 'fr' ? `Accueil de ${host}` : `Homepage of ${host}`;
  }
  const words = pathname
    .split('/')
    .filter(Boolean)
    .flatMap((seg) => seg.split(/[-_]+/))
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1));
  const label = words.join(' ') || pathname;
  return lang === 'fr' ? `Page ${label}` : `${label} page`;
}

function samplePagesOrRoot(report: AuditReport): string[] {
  return report.sampledPages.length > 0 ? report.sampledPages : ['/'];
}

// ---------------------------------------------------------------------------
// generateLlmsTxt
// ---------------------------------------------------------------------------

export function generateLlmsTxt(report: AuditReport, { lang }: GenerateOptions): string {
  const base = new URL(report.url);
  const host = base.host;
  const lines: string[] = [];
  lines.push(`# ${host}`);
  lines.push('');
  lines.push(`<!-- ${warnNote(lang)} -->`);
  lines.push('');
  lines.push(lang === 'fr'
    ? `> Ébauche générée automatiquement pour ${host}. Remplacez ce résumé par 2-3`
    : `> Auto-generated stub for ${host}. Replace this summary with 2-3`);
  lines.push(lang === 'fr'
    ? "> phrases décrivant ce que propose le site et à qui il s'adresse."
    : '> sentences describing what the site offers and who it is for.');
  lines.push('');
  lines.push(lang === 'fr' ? '## Pages' : '## Pages');
  lines.push('');
  for (const p of samplePagesOrRoot(report)) {
    const abs = new URL(p, report.url).toString();
    lines.push(`- [${pageTitle(p, host, lang)}](${abs})`);
  }
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// generateLlmsFullTxt
// ---------------------------------------------------------------------------

export function generateLlmsFullTxt(report: AuditReport, { lang }: GenerateOptions): string {
  const base = new URL(report.url);
  const host = base.host;
  const lines: string[] = [];
  lines.push(lang === 'fr' ? `# ${host} — contenu complet (ébauche générée)` : `# ${host} — full content (generated stub)`);
  lines.push('');
  lines.push(`<!-- ${warnNote(lang)} -->`);
  lines.push('');
  lines.push(lang === 'fr'
    ? 'Ce fichier doit contenir le texte intégral de vos pages clés, sous des titres,'
    : 'This file should hold the full text content of your key pages, under');
  lines.push(lang === 'fr'
    ? "pour les systèmes IA qui récupèrent un document consolidé unique. Ci-dessous,"
    : 'headings, for AI systems that fetch a single consolidated document. Below is');
  lines.push(lang === 'fr'
    ? "une ébauche structurelle : remplacez chaque TODO par le vrai contenu de page."
    : 'a structural stub — replace each TODO with the real page content.');
  lines.push('');
  for (const p of samplePagesOrRoot(report)) {
    lines.push(`## ${pageTitle(p, host, lang)}`);
    lines.push('');
    lines.push(lang === 'fr'
      ? `<!-- TODO : collez ici le texte complet de la page ${p}. -->`
      : `<!-- TODO: paste the full text content of ${p} here. -->`);
    lines.push('');
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// generateAiJson
// ---------------------------------------------------------------------------

export function generateAiJson(report: AuditReport, { lang }: GenerateOptions): string {
  const url = new URL(report.url);
  const obj = {
    name: url.host,
    description: lang === 'fr'
      ? `Ébauche générée automatiquement pour ${url.host}. Remplacez cette description par une présentation réelle du site/de l'organisation.`
      : `Auto-generated stub for ${url.host}. Replace this description with a real summary of the site/organization.`,
    contact: `${url.origin}/`,
    ai_access: {
      training_bots: [...TRAINING_BOTS],
      citation_bots: [...CITATION_BOTS],
      policy: 'allow',
    },
    _note: warnNote(lang),
  };
  return `${JSON.stringify(obj, null, 2)}\n`;
}

// ---------------------------------------------------------------------------
// generateSitemapXml (no {lang}: URLs carry no language-specific content)
// ---------------------------------------------------------------------------

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

export function generateSitemapXml(report: AuditReport): string {
  const urls = samplePagesOrRoot(report).map((p) => new URL(p, report.url).toString());
  const body = urls.map((u) => `  <url>\n    <loc>${escapeXml(u)}</loc>\n  </url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n`
    + `<!-- ${warnText('en')} / ${warnText('fr')} -->\n`
    + `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

// ---------------------------------------------------------------------------
// generateJsonLdStubs
// ---------------------------------------------------------------------------

const STUB_ROOT_TYPES = ['Organization', 'WebSite', 'BreadcrumbList', 'FAQPage'] as const;
type StubRootType = (typeof STUB_ROOT_TYPES)[number];

/** Schema.org @type values already present anywhere in the sampled entity graph (empty when unknown). */
function presentTypes(report: AuditReport): Set<string> {
  const nodes = report.entityGraph?.nodes;
  if (!nodes) return new Set();
  const set = new Set<string>();
  for (const n of nodes) for (const t of n.types) set.add(t);
  return set;
}

export function generateJsonLdStubs(report: AuditReport, { lang }: GenerateOptions): string {
  const url = new URL(report.url);
  const origin = url.origin;
  const host = url.host;
  const present = presentTypes(report);
  const missing: StubRootType[] = STUB_ROOT_TYPES.filter((t) => !present.has(t));

  const orgId = `${origin}/#org`;
  const siteId = `${origin}/#website`;
  const graph: Record<string, unknown>[] = [];

  if (missing.includes('Organization')) {
    graph.push({
      '@type': 'Organization',
      '@id': orgId,
      name: lang === 'fr' ? `<Nom de l'organisation à compléter> (${host})` : `<Organization name to fill in> (${host})`,
      url: `${origin}/`,
      logo: `https://${host}/logo.png`,
      sameAs: [
        'https://en.wikipedia.org/wiki/REPLACE_ME',
        'https://www.wikidata.org/wiki/Q00000000',
      ],
    });
  }
  if (missing.includes('WebSite')) {
    const site: Record<string, unknown> = {
      '@type': 'WebSite',
      '@id': siteId,
      url: `${origin}/`,
      name: lang === 'fr' ? '<Nom du site à compléter>' : '<Site name to fill in>',
      potentialAction: {
        '@type': 'SearchAction',
        target: { '@type': 'EntryPoint', urlTemplate: `${origin}/search?q={search_term_string}` },
        'query-input': 'required name=search_term_string',
      },
    };
    if (missing.includes('Organization')) site.publisher = { '@id': orgId };
    graph.push(site);
  }
  if (missing.includes('BreadcrumbList')) {
    graph.push({
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: lang === 'fr' ? 'Accueil' : 'Home', item: `${origin}/` },
        { '@type': 'ListItem', position: 2, name: lang === 'fr' ? '<Page actuelle à compléter>' : '<Current page to fill in>' },
      ],
    });
  }
  if (missing.includes('FAQPage')) {
    graph.push({
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: lang === 'fr' ? '<Question exemple à compléter>' : '<Example question to fill in>',
          acceptedAnswer: {
            '@type': 'Answer',
            text: lang === 'fr' ? '<Réponse exemple à compléter>' : '<Example answer to fill in>',
          },
        },
      ],
    });
  }

  const extra = graph.length === 0
    ? (lang === 'fr'
      ? ' Aucune ébauche nécessaire : Organization, WebSite, BreadcrumbList et FAQPage sont déjà présents sur le site.'
      : ' No stub needed: Organization, WebSite, BreadcrumbList and FAQPage are already present on the site.')
    : (lang === 'fr'
      ? ' Fusionnez ce @graph avec votre JSON-LD existant, ou ajoutez-le comme nouveau <script type="application/ld+json">.'
      : ' Merge this @graph into your existing JSON-LD, or add it as a new <script type="application/ld+json">.');

  const out = {
    '@context': 'https://schema.org',
    '@graph': graph,
    _note: `${warnNote(lang)}${extra}`,
  };
  return `${JSON.stringify(out, null, 2)}\n`;
}

// ---------------------------------------------------------------------------
// EMITTED_FILES — single source of truth shared with the CLI (--emit) and web
// (self-apply) surfaces, wired up by later tasks.
// ---------------------------------------------------------------------------

export interface EmittedFile {
  /** Relative path within the output directory (may include subdirectories, e.g. ".well-known/ai.json"). */
  filename: string;
  mime: string;
  build(report: AuditReport, opts: GenerateOptions): string;
}

export const EMITTED_FILES: ReadonlyArray<EmittedFile> = [
  { filename: 'robots.txt', mime: 'text/plain', build: generateRobotsTxt },
  { filename: 'llms.txt', mime: 'text/plain', build: generateLlmsTxt },
  { filename: 'llms-full.txt', mime: 'text/plain', build: generateLlmsFullTxt },
  { filename: '.well-known/ai.json', mime: 'application/json', build: generateAiJson },
  { filename: 'sitemap.xml', mime: 'application/xml', build: (report) => generateSitemapXml(report) },
  { filename: 'jsonld-stubs.json', mime: 'application/json', build: generateJsonLdStubs },
];

// ---------------------------------------------------------------------------
// generateReadme + emitFiles
// ---------------------------------------------------------------------------

export function generateReadme(report: AuditReport, { lang }: GenerateOptions): string {
  const host = new URL(report.url).host;
  const title = lang === 'fr' ? `Fichiers générés pour ${host}` : `Generated files for ${host}`;
  const intro = lang === 'fr'
    ? `Ces fichiers ont été générés automatiquement par findable-audit à partir de l'audit de ${host}. ${warnText(lang)} Bloquer un crawler IA par erreur peut retirer votre site des réponses générées par IA.`
    : `These files were auto-generated by findable-audit from the audit of ${host}. ${warnText(lang)} Accidentally blocking an AI crawler can remove your site from AI-generated answers.`;
  const list = EMITTED_FILES.map((f) => `- \`${f.filename}\``).join('\n');
  const placement = lang === 'fr'
    ? 'Placez `robots.txt`, `llms.txt`, `llms-full.txt` et `sitemap.xml` à la racine du site, et `.well-known/ai.json` sous `/.well-known/`. Le contenu de `jsonld-stubs.json` est à fusionner dans le JSON-LD existant de vos pages (balise `<script type="application/ld+json">`).'
    : 'Place `robots.txt`, `llms.txt`, `llms-full.txt` and `sitemap.xml` at the site root, and `.well-known/ai.json` under `/.well-known/`. The content of `jsonld-stubs.json` should be merged into your pages\' existing JSON-LD (`<script type="application/ld+json">` tag).';
  return [
    `# ${title}`,
    '',
    intro,
    '',
    lang === 'fr' ? '## Fichiers' : '## Files',
    '',
    list,
    '',
    placement,
    '',
  ].join('\n');
}

/** Write every EMITTED_FILES entry plus GENERATED-README.md into `dir`. Returns the written paths. */
export function emitFiles(report: AuditReport, dir: string, { lang }: GenerateOptions): string[] {
  const written: string[] = [];
  for (const entry of EMITTED_FILES) {
    const full = path.join(dir, entry.filename);
    mkdirSync(path.dirname(full), { recursive: true });
    writeFileSync(full, entry.build(report, { lang }), 'utf8');
    written.push(full);
  }
  const readmePath = path.join(dir, 'GENERATED-README.md');
  mkdirSync(dir, { recursive: true });
  writeFileSync(readmePath, generateReadme(report, { lang }), 'utf8');
  written.push(readmePath);
  return written;
}
