import type { AuditReport } from '../runner.js';
import type { CheckResult, Family } from '../types.js';
import { FAMILY_LABELS } from './terminal.js';

const STATUS_LABEL: Record<CheckResult['status'], string> = {
  pass: 'PASS', warn: 'WARN', fail: 'FAIL', skip: 'SKIP',
};

/** Escape text for safe inclusion in HTML (the report contains site-derived strings). */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function scoreClass(score: number): string {
  return score >= 80 ? 'good' : score >= 60 ? 'ok' : 'bad';
}

const STYLE = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font: 15px/1.5 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    color: #1a1a1a; background: #fff; margin: 0; padding: 2rem; max-width: 860px; }
  h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
  h2 { font-size: 1.1rem; margin: 1.75rem 0 .5rem; border-bottom: 1px solid #e5e5e5; padding-bottom: .25rem; }
  .meta { color: #666; font-size: .9rem; margin-bottom: 1rem; }
  .score { display: inline-block; font-weight: 700; font-size: 1.1rem; padding: .35rem .8rem;
    border-radius: 6px; color: #fff; }
  .score.good { background: #1a7f37; } .score.ok { background: #9a6700; } .score.bad { background: #b42318; }
  .pages { color: #444; font-size: .85rem; margin: .5rem 0 0; }
  table { width: 100%; border-collapse: collapse; margin: .25rem 0; }
  td { padding: .4rem .5rem; border-bottom: 1px solid #f0f0f0; vertical-align: top; }
  td.st { white-space: nowrap; font-weight: 700; font-size: .8rem; width: 3.5rem; }
  td.pts { white-space: nowrap; text-align: right; color: #555; width: 3.5rem; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .85em; }
  .st.pass { color: #1a7f37; } .st.warn { color: #9a6700; } .st.fail { color: #b42318; } .st.skip { color: #999; }
  .fix { color: #555; font-size: .85rem; margin-top: .15rem; }
  .msg { color: #333; font-size: .9rem; margin-top: .1rem; }
  .row { break-inside: avoid; }
  footer { margin-top: 2rem; color: #888; font-size: .8rem; border-top: 1px solid #e5e5e5; padding-top: .75rem; }
  @media print {
    body { padding: 0; max-width: none; }
    h2, tr { break-inside: avoid; }
  }
`;

export function renderHtml(report: AuditReport, now: Date = new Date()): string {
  const date = now.toISOString().slice(0, 10);
  const families = Object.keys(FAMILY_LABELS) as Family[];
  const sections: string[] = [];

  for (const family of families) {
    const results = report.results.filter((r) => r.family === family);
    if (results.length === 0) continue;
    const earned = results.reduce((s, r) => (r.status === 'skip' ? s : s + r.points), 0);
    const max = results.reduce((s, r) => (r.status === 'skip' ? s : s + r.maxPoints), 0);
    const rows = results.map((r) => {
      const fix = r.fix && r.status !== 'pass' && r.status !== 'skip'
        ? `<div class="fix">${escapeHtml(r.fix)}</div>` : '';
      return `<tr class="row">
        <td class="st ${r.status}">${STATUS_LABEL[r.status]}</td>
        <td><code>${escapeHtml(r.id)}</code><div class="msg">${escapeHtml(r.message)}</div>${fix}</td>
        <td class="pts">${r.points}/${r.maxPoints}</td>
      </tr>`;
    }).join('\n');
    sections.push(`<h2>${escapeHtml(FAMILY_LABELS[family])} <span class="pts">(${earned}/${max})</span></h2>
      <table>${rows}</table>`);
  }

  const pages = report.sampledPages.map((p) => `<code>${escapeHtml(p)}</code>`).join(', ');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>findable-audit report — ${escapeHtml(report.url)}</title>
<style>${STYLE}</style>
</head>
<body>
<h1>findable-audit report</h1>
<div class="meta">${escapeHtml(report.url)} · ${date}</div>
<p><span class="score ${scoreClass(report.score)}">Score: ${report.score}/100 · Grade ${escapeHtml(report.grade)}</span></p>
<p class="pages">Pages audited: ${pages}</p>
${sections.join('\n')}
<footer>Generated by findable-audit · https://github.com/piwig/findable-audit</footer>
</body>
</html>
`;
}
