import type { Grade } from '../scoring.js';
import type { Family } from '../types.js';

export type Lang = 'en' | 'fr';

/** Bucket keys shared with cwv.ts (kept literal to avoid a runtime import cycle). */
type CwvBucketKey = 'good' | 'ni' | 'poor';
type CwvAssessKey = 'passed' | 'average' | 'slow' | 'inconclusive';
type CwvMetricKey = 'lcp' | 'inp' | 'cls' | 'ttfb';
type EffortKey = 'quick' | 'moderate' | 'involved';

/** Every report-chrome label. The 112 checks' own message/fix text is NOT here. */
export interface ReportMessages {
  // document chrome
  reportTitle: string;   // HTML <h1> + <title> prefix
  mdTitle: string;       // Markdown <h1> brand
  gradeLabel: string;    // grade badge / score line prefix
  outOf100: string;      // "/100" suffix in the hero
  categorySubscores: string;
  pagesAudited: string;  // HTML "Pages audited:" line label
  learnMore: string;     // doc-link anchor text
  footer: string;        // HTML footer line
  // hero stats + verdict
  stats: (passed: number, toFix: number, pages: number) => string;
  verdict: (grade: Grade, failCount: number) => string;
  // action plan
  actionPlan: string;
  fixFirst: string;      // fails group heading
  improve: string;       // warns group heading
  moreRecs: (n: number) => string;
  pts: string;           // impact unit
  // markdown-only chrome
  mdScore: string;                 // "Score:" label
  mdSubscoreHeader: string;        // subscore table header row
  mdCheckHeader: string;           // per-family check table header row
  mdRecommendedFixes: string;      // recommendations heading
  mdDoc: string;                   // "doc" link text
  mdFooter: string;                // footer line
  // Core Web Vitals chrome
  cwvTitle: string;
  cwvNotMeasured: string;          // HTML note (contains <code> markup)
  cwvBucket: Record<CwvBucketKey, string>;
  cwvMdStatus: Record<CwvBucketKey, string>;
  cwvAssess: Record<CwvAssessKey, string>;
  cwvSrcOrigin: string;            // HTML "CrUX origin"
  cwvSrcField: string;             // HTML "CrUX field"
  cwvMdHeader: string;             // CWV markdown table header row
  cwvMdSrcOrigin: string;          // CWV markdown source cell
  cwvMdSrcField: string;
  cwvLabPrefix: string;            // HTML lab line prefix
  cwvLabTag: string;               // HTML lab tag text
  cwvLabMdPrefix: string;          // markdown lab line prefix
  // CWV explainer + advice box (#5) — bilingual
  cwvIntro: string;                // one-paragraph what/why (field vs lab)
  cwvExplainTitle: string;         // "What these metrics mean"
  cwvAdviceTitle: string;          // "How to improve"
  cwvAllGood: string;              // shown when every measured metric is "good"
  cwvMetricInfo: Record<CwvMetricKey, { label: string; what: string; advice: string }>;
  cwvKpiHeader: { metric: string; value: string; rating: string; good: string; poor: string }; // KPI table (#2b)
  // action-plan effort estimate (#18)
  effortLabel: Record<EffortKey, string>;
  // competitive comparison (#36)
  compareTitle: string;
  compareYou: string;
  compareOverall: string;
  compareGapsTitle: string;
  compareNoGaps: string;
  compareBehind: string; // suffix on a gap line, e.g. "-12 behind the leader"
  compareCwvNote: string; // shown when the compared audits skipped Core Web Vitals (lightweight mode)
  // collapsible family summary status (accessible name for the color dot)
  famStatus: { bad: string; ok: string; good: string };
}

export const MESSAGES: Record<Lang, ReportMessages> = {
  en: {
    reportTitle: 'findable-audit report',
    mdTitle: 'findable-audit',
    gradeLabel: 'Grade',
    outOf100: '/100',
    categorySubscores: 'Category subscores',
    pagesAudited: 'Pages audited:',
    learnMore: 'Learn more →',
    footer: 'Generated by findable-audit · https://github.com/piwig/findable-audit',
    stats: (passed, toFix, pages) => `${passed} passed · ${toFix} to fix · ${pages} pages`,
    verdict: (grade, n) => {
      switch (grade) {
        case 'A': return n === 0 ? 'Excellent — top-tier AI findability.' : `Very good — ${n} point(s) to polish.`;
        case 'B': return `Solid base — ${n} priority(ies) to reach an A.`;
        case 'C': return `Decent — ${n} priority issue(s) holding back findability.`;
        case 'D': return `Fragile — ${n} important fix(es) to address.`;
        default:  return `Foundations to fix — ${n} critical point(s).`;
      }
    },
    actionPlan: 'Action plan',
    fixFirst: '🔴 Fix first',
    improve: '🟠 Improve',
    moreRecs: (n) => `+${n} more — see the per-family detail below.`,
    pts: 'pts',
    mdScore: 'Score:',
    mdSubscoreHeader: '| Family | Subscore | Weight | Earned/Max |',
    mdCheckHeader: '| | Check | Points | Result |',
    mdRecommendedFixes: 'Recommended fixes',
    mdDoc: 'doc',
    mdFooter: '_Generated by [findable-audit](https://github.com/piwig/findable-audit)_',
    cwvTitle: 'Core Web Vitals',
    cwvNotMeasured: 'Core Web Vitals not measured — run with <code>--cwv --psi-key &lt;key&gt;</code>.',
    cwvBucket: { good: 'good', ni: 'needs improvement', poor: 'poor' },
    cwvMdStatus: { good: '✅ Good', ni: '⚠️ Needs improvement', poor: '❌ Poor' },
    cwvAssess: { passed: 'PASSED', average: 'NEEDS WORK', slow: 'FAILED', inconclusive: 'INCONCLUSIVE' },
    cwvSrcOrigin: 'CrUX origin',
    cwvSrcField: 'CrUX field',
    cwvMdHeader: '| Metric | p75 | Status | Source |',
    cwvMdSrcOrigin: 'origin',
    cwvMdSrcField: 'field',
    cwvLabPrefix: 'Lighthouse lab: Perf',
    cwvLabTag: 'lab',
    cwvLabMdPrefix: 'Lab (Lighthouse): Perf',
    cwvIntro: 'Core Web Vitals are Google’s user-experience signals (loading, interactivity, visual stability). They affect both search ranking and how real visitors perceive the site. Field data reflects real Chrome users (CrUX); lab data is a single controlled test.',
    cwvExplainTitle: 'What these metrics mean',
    cwvAdviceTitle: 'How to improve',
    cwvAllGood: 'Every measured metric is in the “good” range — nice work.',
    cwvMetricInfo: {
      lcp: { label: 'LCP — Largest Contentful Paint', what: 'time until the main content is visible', advice: 'Optimize the hero image (compress, size correctly, preload), cut render-blocking CSS/JS, and serve from a CDN.' },
      inp: { label: 'INP — Interaction to Next Paint', what: 'how quickly the page reacts to interactions', advice: 'Break up long JavaScript tasks, defer non-critical scripts, and avoid heavy work on click/input.' },
      cls: { label: 'CLS — Cumulative Layout Shift', what: 'visual stability (unexpected layout jumps)', advice: 'Set width/height on images and embeds, reserve space for ads/banners, and never inject content above existing content.' },
      ttfb: { label: 'TTFB — Time to First Byte', what: 'server response time (a diagnostic — not one of the three official Core Web Vitals)', advice: 'Speed up the backend, enable caching, use a CDN, and remove needless redirects.' },
    },
    cwvKpiHeader: { metric: 'Metric', value: 'Value (p75)', rating: 'Rating', good: 'Good', poor: 'Poor' },
    effortLabel: { quick: 'Quick win', moderate: 'Moderate', involved: 'Involved' },
    compareTitle: 'Competitive comparison',
    compareYou: 'You',
    compareOverall: 'Overall score',
    compareGapsTitle: 'Where you trail',
    compareNoGaps: 'You lead or match on every family — nice.',
    compareBehind: 'behind the leader',
    compareCwvNote: 'Core Web Vitals are not measured in comparison mode (lightweight audits).',
    famStatus: { bad: 'Needs fixes', ok: 'Warnings only', good: 'All passing' },
  },
  fr: {
    reportTitle: 'Rapport findable-audit',
    mdTitle: 'findable-audit',
    gradeLabel: 'Note',
    outOf100: '/100',
    categorySubscores: 'Sous-scores par catégorie',
    pagesAudited: 'Pages auditées :',
    learnMore: 'En savoir plus →',
    footer: 'Généré par findable-audit · https://github.com/piwig/findable-audit',
    stats: (passed, toFix, pages) => `${passed} réussis · ${toFix} à corriger · ${pages} pages`,
    verdict: (grade, n) => {
      switch (grade) {
        case 'A': return n === 0 ? 'Excellent — findabilité IA au top.' : `Très bon — ${n} point(s) à polir.`;
        case 'B': return `Bonne base — ${n} priorité(s) pour viser A.`;
        case 'C': return `Correct — ${n} priorité(s) freinent la findabilité.`;
        case 'D': return `Fragile — ${n} correction(s) importantes à traiter.`;
        default:  return `Fondations à corriger : ${n} point(s) critique(s).`;
      }
    },
    actionPlan: "Plan d'action",
    fixFirst: '🔴 À corriger en priorité',
    improve: '🟠 À améliorer',
    moreRecs: (n) => `+${n} autre(s) — voir le détail par famille ci-dessous.`,
    pts: 'pts',
    mdScore: 'Score :',
    mdSubscoreHeader: '| Famille | Sous-score | Poids | Acquis/Max |',
    mdCheckHeader: '| | Contrôle | Points | Résultat |',
    mdRecommendedFixes: 'Corrections recommandées',
    mdDoc: 'doc',
    mdFooter: '_Généré par [findable-audit](https://github.com/piwig/findable-audit)_',
    cwvTitle: 'Core Web Vitals',
    cwvNotMeasured: 'Core Web Vitals non mesurés — lancez avec <code>--cwv --psi-key &lt;clé&gt;</code>.',
    cwvBucket: { good: 'bon', ni: 'à améliorer', poor: 'mauvais' },
    cwvMdStatus: { good: '✅ Bon', ni: '⚠️ À améliorer', poor: '❌ Mauvais' },
    cwvAssess: { passed: 'RÉUSSI', average: 'À AMÉLIORER', slow: 'ÉCHEC', inconclusive: 'NON CONCLUANT' },
    cwvSrcOrigin: 'CrUX origine',
    cwvSrcField: 'CrUX terrain',
    cwvMdHeader: '| Métrique | p75 | Statut | Source |',
    cwvMdSrcOrigin: 'origine',
    cwvMdSrcField: 'terrain',
    cwvLabPrefix: 'Labo Lighthouse : Perf',
    cwvLabTag: 'labo',
    cwvLabMdPrefix: 'Labo (Lighthouse) : Perf',
    cwvIntro: 'Les Core Web Vitals sont les signaux d’expérience utilisateur de Google (chargement, interactivité, stabilité visuelle). Ils influencent le référencement et la perception des vrais visiteurs. Les données terrain reflètent de vrais utilisateurs Chrome (CrUX) ; les données labo sont un test contrôlé unique.',
    cwvExplainTitle: 'Ce que mesurent ces indicateurs',
    cwvAdviceTitle: 'Comment améliorer',
    cwvAllGood: 'Tous les indicateurs mesurés sont au vert — beau travail.',
    cwvMetricInfo: {
      lcp: { label: 'LCP — Largest Contentful Paint', what: 'temps avant l’affichage du contenu principal', advice: 'Optimisez l’image principale (compression, dimensions, préchargement), réduisez le CSS/JS bloquant et servez via un CDN.' },
      inp: { label: 'INP — Interaction to Next Paint', what: 'rapidité de réaction de la page aux interactions', advice: 'Découpez les longues tâches JavaScript, différez les scripts non essentiels et évitez le travail lourd au clic/à la saisie.' },
      cls: { label: 'CLS — Cumulative Layout Shift', what: 'stabilité visuelle (sauts de mise en page)', advice: 'Fixez les dimensions des images/embeds, réservez l’espace des pubs/bannières et n’insérez jamais de contenu au-dessus de l’existant.' },
      ttfb: { label: 'TTFB — Time to First Byte', what: 'temps de réponse du serveur (un diagnostic — pas l’un des trois Core Web Vitals officiels)', advice: 'Accélérez le backend, activez le cache, utilisez un CDN et supprimez les redirections inutiles.' },
    },
    cwvKpiHeader: { metric: 'Métrique', value: 'Valeur (p75)', rating: 'Évaluation', good: 'Bon', poor: 'Mauvais' },
    effortLabel: { quick: 'Rapide', moderate: 'Modéré', involved: 'Conséquent' },
    compareTitle: 'Comparaison concurrentielle',
    compareYou: 'Vous',
    compareOverall: 'Score global',
    compareGapsTitle: 'Où vous êtes devancé',
    compareNoGaps: 'Vous êtes en tête ou à égalité sur chaque famille — beau travail.',
    compareBehind: 'sous le leader',
    compareCwvNote: 'Core Web Vitals non mesurés en mode comparaison (audits allégés).',
    famStatus: { bad: 'À corriger', ok: 'Avertissements', good: 'Tout passe' },
  },
};

export function messages(lang: Lang): ReportMessages {
  return MESSAGES[lang];
}

/**
 * Family display labels per language. Order is canonical (matches FAMILY_WEIGHTS
 * / renderers). EN values equal the Phase-1 terminal labels so terminal output
 * is unchanged when it re-derives from the EN entries.
 */
export const FAMILY_LABELS_I18N: Record<Lang, Record<Family, string>> = {
  en: {
    'ai-access': 'AI crawler access',
    'llm-content': 'Answer-engine content',
    'structured-data': 'Structured data & metadata',
    'technical-seo': 'Technical SEO',
    'on-page': 'On-page & content',
    performance: 'Performance & Core Web Vitals',
    accessibility: 'Accessibility',
    security: 'Security & trust',
  },
  fr: {
    'ai-access': 'Accès crawler IA',
    'llm-content': 'Contenu moteur de réponse',
    'structured-data': 'Données structurées & métadonnées',
    'technical-seo': 'SEO technique',
    'on-page': 'On-page & contenu',
    performance: 'Performance & Core Web Vitals',
    accessibility: 'Accessibilité',
    security: 'Sécurité & confiance',
  },
};

/** Short family chips for the action plan / compact UI. */
export const FAMILY_SHORT_I18N: Record<Lang, Record<Family, string>> = {
  en: {
    'ai-access': 'AI access',
    'llm-content': 'AI content',
    'structured-data': 'Data',
    'technical-seo': 'SEO',
    'on-page': 'On-page',
    performance: 'Perf',
    accessibility: 'A11y',
    security: 'Security',
  },
  fr: {
    'ai-access': 'Accès IA',
    'llm-content': 'Contenu IA',
    'structured-data': 'Données',
    'technical-seo': 'SEO',
    'on-page': 'On-page',
    performance: 'Perf',
    accessibility: 'A11y',
    security: 'Sécurité',
  },
};
