import type { AuditReport } from '../runner.js';
import type { CheckResult, Family } from '../types.js';
import { FAMILY_LABELS } from './terminal.js';
import { verdictOf } from './verdict.js';
import { renderCwvMarkdown } from './cwv.js';
import { collectRecommendations } from './recommendations.js';

const ICONS: Record<CheckResult['status'], string> = {
  pass: '✅', warn: '⚠️', fail: '❌', skip: '⏭️',
};

/** Escape characters that would break a Markdown table cell. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

export function renderMarkdown(report: AuditReport, now: Date = new Date()): string {
  const failCount = report.results.filter((r) => r.status === 'fail').length;
  const lines: string[] = [
    `# findable-audit — ${report.url}`,
    '',
    `**Score: ${report.score}/100** · **Grade ${report.grade}** — ${now.toISOString().slice(0, 10)}`,
    '',
    `> ${verdictOf(report.grade, failCount)}`,
    '',
  ];

  if (report.familyScores.length > 0) {
    lines.push('## Category subscores', '');
    lines.push('| Family | Subscore | Weight | Earned/Max |');
    lines.push('|---|---|---|---|');
    for (const fs of report.familyScores) {
      const weightPct = Math.round(fs.weight * 100);
      lines.push(`| ${cell(FAMILY_LABELS[fs.family])} | ${fs.score}/100 | ${weightPct}% | ${fs.earned}/${fs.max} |`);
    }
    lines.push('');
  }

  if (report.psi) {
    lines.push(renderCwvMarkdown(report.psi), '');
  }

  for (const family of Object.keys(FAMILY_LABELS) as Family[]) {
    const results = report.results.filter((r) => r.family === family);
    if (results.length === 0) continue;
    const earned = results.reduce((s, r) => (r.status === 'skip' ? s : s + r.points), 0);
    const max = results.reduce((s, r) => (r.status === 'skip' ? s : s + r.maxPoints), 0);
    lines.push(`## ${FAMILY_LABELS[family]} (${earned}/${max})`, '');
    lines.push('| | Check | Points | Result |');
    lines.push('|---|---|---|---|');
    for (const r of results) {
      lines.push(`| ${ICONS[r.status]} | \`${r.id}\` | ${r.points}/${r.maxPoints} | ${cell(r.message)} |`);
    }
    lines.push('');
  }

  const recs = collectRecommendations(report.results);
  if (recs.length > 0) {
    lines.push('## Recommended fixes', '');
    for (const r of recs) {
      const link = r.docUrl ? ` — [doc](${r.docUrl})` : '';
      lines.push(`- ${ICONS[r.status]} **\`${r.id}\`** (+${r.impact} pts) — ${r.fix}${link}`);
    }
    lines.push('');
  }

  lines.push('---', '', '_Generated by [findable-audit](https://github.com/piwig/findable-audit)_', '');
  return lines.join('\n');
}
