import type { AuditReport } from '../runner.js';
import type { CheckResult, Family } from '../types.js';

const FAMILY_LABELS: Record<Family, string> = {
  'ai-access': 'AI crawler access',
  'llm-content': 'Content for LLMs',
  'structured-data': 'Structured data',
  'seo-fundamentals': 'SEO fundamentals',
};

const ICONS: Record<CheckResult['status'], string> = {
  pass: '✅', warn: '⚠️', fail: '❌', skip: '⏭️',
};

/** Escape characters that would break a Markdown table cell. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

export function renderMarkdown(report: AuditReport, now: Date = new Date()): string {
  const lines: string[] = [
    `# findable-audit — ${report.url}`,
    '',
    `**Score: ${report.score}/100** — ${now.toISOString().slice(0, 10)}`,
    '',
  ];

  for (const family of Object.keys(FAMILY_LABELS) as Family[]) {
    const results = report.results.filter((r) => r.family === family);
    if (results.length === 0) continue;
    const earned = results.reduce((s, r) => (r.status === 'skip' ? s : s + r.points), 0);
    const max = results.reduce((s, r) => (r.status === 'skip' ? s : s + r.maxPoints), 0);
    lines.push(`## ${FAMILY_LABELS[family]} (${earned}/${max})`, '');
    lines.push('| | Check | Points | Result |');
    lines.push('|---|---|---|---|');
    for (const r of results) {
      lines.push(`| ${ICONS[r.status]} | \`${r.id}\` | ${r.points}/${r.maxPoints} | ${cell(r.message)} |`);
    }
    lines.push('');
  }

  const fixes = report.results.filter((r) => r.fix && (r.status === 'fail' || r.status === 'warn'));
  if (fixes.length > 0) {
    lines.push('## Recommended fixes', '');
    // Fails first (biggest wins), then warns.
    fixes.sort((a, b) => (a.status === b.status ? b.maxPoints - a.maxPoints : a.status === 'fail' ? -1 : 1));
    for (const r of fixes) {
      lines.push(`- ${ICONS[r.status]} **\`${r.id}\`** — ${r.fix}`);
    }
    lines.push('');
  }

  lines.push('---', '', '_Generated by [findable-audit](https://github.com/piwig/findable-audit)_', '');
  return lines.join('\n');
}
